### ISSUE TITLE
Dynamic/Unknown height?

### ISSUE THREAD

**Issue by ysk3a** [lVlyke/lithium-ngx-virtual-scroll#19]
Cool library!

Any support for dynamic height?

Based on the https://github.com/lVlyke/lithium-ngx-virtual-scroll#inputs , the itemHeight if not set is automatic. 
What is it automatically doing? Setting a single height or per item? Just wanted to understand how it works.

I tried to modify the demo https://github.com/lVlyke/lithium-ngx-virtual-scroll-demo to mimic 'random-ish' height per item by:
item-widget.component.scss add display block to img tag
```css
  img {
    object-fit: contain;
    max-width: 100%;
    max-height: 100%;
    display: block;

  }
```
item-widget.component.ts add
```ts
  randomHeight: number = Math.floor(Math.random() * (10 - 1) + 1);
  randomList: number[] = Array.from({ length: this.randomHeight }, (_, i) => i + 1)
```
item-widget.component.html change to
```html
<ng-container *ngFor="let item of randomList">
  <img src="{{baseHref}}/favicon.ico">
</ng-container>
```
app.component.scss comment out height property
```css
>.list-item {
      display: flex;
      justify-content: space-between;
      border-bottom: 1px solid #ccc;
      // height: 1.5rem;
...
   }
```
I can't confirm expected behavior in, lets say, a fresh angular project is normal but based on those few modification to the demo, it seems to work somewhat. scrolling sometimes makes the items really jumpy.
Also, it seems that if you change the randomHeight to something like 20 or 40 you get a warning that scroll reached limit because of MAX_SCROLL_HEIGHT_PX. So does this mean the amount of items that can be rendered in the virtual scroll is limited to the max height since if it is required?
This is in list mode not grid layout mode.

This part is kind of separate but any plans on add a working codesandbox or stackblitz demo link? forking the demo repo directly to those online editors seemed to error out.
